spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      schema: mydb
    username: postgres
    password: ramana
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true